apiVersion: apps/v1
kind: Deployment
metadata:
  name: "netflix-website"
  namespace: netflix-website
  labels:
    app: "nginx"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: netflix-website
  template:
    metadata:
      labels:
        app: netflix-website
    spec:
      restartPolicy: Always
      containers:
      - name: netflix-website
        image: "ianang/web-html-css:latest"
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
