apiVersion: v1
kind: Service
metadata:
  name: netflix-website-service
  namespace: netflix-nebsite
spec:
  selector:
    app: netflix-nebsite
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
